name: Publish Report

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  publish_report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build and generate report
        run: |
          mvn clean install
          mvn site

      - name: Publish report
        uses: actions/upload-artifact@v2
        with:
          name: Report
          path: target/site
